### PR TITLE
Remove unneeded SES email identity

### PR DESCRIPTION
**Pull request by strugee**

### CODE REVIEW

**Review by sntxrr — CHANGES_REQUESTED** [review]
I think we also want to yank the `rua=` from [here](https://github.com/SeaGL/seagl-terraform/blob/main/dns.tf#L55) as well

**Comment by sntxrr** [comment]
@strugee not sure if you saw my feedback on this PR - I think there is another place to remove the email

**Comment by strugee** [comment]
@sntxrr I don't think this is a problem since 063f76e3fcfc5930078ade66c064dbfffc52bdfa landed?

**Comment by strugee** [comment]
Closing since this has bitrotted and will be even more bitrotted after #49 - which includes a TODO comment about removing this anyway - lands.

**Pull request closed without merging**
